// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAReTP9ZIBLzRolyTKJsIswRmKPaSFROgo',
    appId: '1:1090717559226:web:6f343913fc04f39faf1583',
    messagingSenderId: '1090717559226',
    projectId: 'projectmoapp-a4562',
    authDomain: 'projectmoapp-a4562.firebaseapp.com',
    storageBucket: 'projectmoapp-a4562.appspot.com',
    measurementId: 'G-6EZ0LT8F2F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3BhITd9iyN0o2mnkzx9EEpv3aCM54Iw4',
    appId: '1:1090717559226:android:f34c165c83e32be3af1583',
    messagingSenderId: '1090717559226',
    projectId: 'projectmoapp-a4562',
    storageBucket: 'projectmoapp-a4562.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaVfvu3A76YQaOLXREsbrkltglefwpOWE',
    appId: '1:1090717559226:ios:7d5bd33cd2fb6351af1583',
    messagingSenderId: '1090717559226',
    projectId: 'projectmoapp-a4562',
    storageBucket: 'projectmoapp-a4562.appspot.com',
    iosBundleId: 'com.example.mobileappProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaVfvu3A76YQaOLXREsbrkltglefwpOWE',
    appId: '1:1090717559226:ios:ddd32a4115475743af1583',
    messagingSenderId: '1090717559226',
    projectId: 'projectmoapp-a4562',
    storageBucket: 'projectmoapp-a4562.appspot.com',
    iosBundleId: 'com.example.mobileappProject.RunnerTests',
  );
}
